/* Write your T-SQL query statement below */


SELECT
    patient_id,
    patient_name,
    conditions
FROM
    Patients
CROSS APPLY
    STRING_SPLIT(conditions, ' ')
WHERE
    value like 'DIAB1%'

/*
STRING_SPLIT is a table-valued function which splits the string based on the delimiter and generates a new row for each split string and these are stored in a implicit column generated by STRING_SPLIT called value 

CROSS APPLY would join the table with the result of STRING_SPLIT
And STRING_SPLIT is executed for each row the table
*/